modLoader = "javafml"
loaderVersion = "[0,)"
license = "${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="logo.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
mandatory = true
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
mandatory = true
versionRange = "[6.0.10,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "deeperdarker"
mandatory = true
versionRange = "[1.4.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config="deepdivinggear.mixins.json"
